apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: AndrianjafyToky_TP_DesignPattern
  description: AndrianjafyToky_TP_DesignPattern (Java)
  annotations:
    github.com/project-slug: tokyandria001/AndrianjafyToky_TP_DesignPattern
  tags:
    - java
spec:
  type: service
  lifecycle: experimental
  owner: guests
